# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff63817b4639354fe30c4ed9e83af912644a355840f50eb1cc0fb0a01244f5a05afd396619e2eab891da2abd46362704f2e73cf09062167d22c348f036d26d1

test:
  secret_key_base: 2f45f3e1703e4fc591d88e78aaef67aab592ac3cd0f6f10ff75e96305fb7bb4b49f87dcfcb423fa048120ab8a302aaf1f3cc843a872188d74b36cebbbc63d31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
